# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true      # Dependencies automatisch injizieren
        autoconfigure: true # Services automatisch registrieren (z.B. EventListener)
        bind:
            $projectDir: '%kernel.project_dir%'

 
    App\EventListener\LogoutSuccessListener:
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LogoutEvent, method: onLogoutSuccess }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

  
