parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
